apiVersion: v1
kind: ConfigMap
metadata:
  name: search-engine-config
  namespace: default
data:
  DOBRIKA_ADDR: "0.0.0.0"
  DOBRIKA_PORT: "8080"
  DOBRIKA_DB_PATH: "/app/db"
  DOBRIKA_COLD_MIN: "30"
  DOBRIKA_HOT_MIN: "15"
  DOBRIKA_SEARCH_OFFSET: "0"
  DOBRIKA_SEARCH_LIMIT: "20"
  DOBRIKA_GEO_INDEX: "2"
