apiVersion: v1
kind: Service
metadata:
  name: search-engine
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: search-engine
  ports:
    - name: http
      port: 8080
      targetPort: http

